const MONTHS = [
  { month_value: 1, month: "Ιανουάριος" },
  { month_value: 2, month: "Φεβρουάριος" },
  { month_value: 3, month: "Μάρτιος" },
  { month_value: 4, month: "Απρίλιος" },
  { month_value: 5, month: "Μάιος" },
  { month_value: 6, month: "Ιούνιος" },
  { month_value: 7, month: "Ιούλιος" },
  { month_value: 8, month: "Αύγουστος" },
  { month_value: 9, month: "Σεπτέμβριος" },
  { month_value: 10, month: "Οκτώβριος" },
  { month_value: 11, month: "Νοέμβριος" },
  { month_value: 12, month: "Δεκέμβριος" },
];

const DAYS = [
  { day_value: 1, day: "1" },
  { day_value: 2, day: "2" },
  { day_value: 3, day: "3" },
  { day_value: 4, day: "4" },
  { day_value: 5, day: "5" },
  { day_value: 6, day: "6" },
  { day_value: 7, day: "7" },
  { day_value: 8, day: "8" },
  { day_value: 9, day: "9" },
  { day_value: 10, day: "10" },
  { day_value: 11, day: "11" },
  { day_value: 12, day: "12" },
  { day_value: 13, day: "13" },
  { day_value: 14, day: "14" },
  { day_value: 15, day: "15" },
  { day_value: 16, day: "16" },
  { day_value: 17, day: "17" },
  { day_value: 18, day: "18" },
  { day_value: 19, day: "19" },
  { day_value: 20, day: "20" },
  { day_value: 21, day: "21" },
  { day_value: 22, day: "22" },
  { day_value: 23, day: "23" },
  { day_value: 24, day: "24" },
  { day_value: 25, day: "25" },
  { day_value: 26, day: "26" },
  { day_value: 27, day: "27" },
  { day_value: 28, day: "28" },
  { day_value: 29, day: "29" },
  { day_value: 30, day: "30" },
  { day_value: 31, day: "31" },
];

export { MONTHS, DAYS };
